# Generated by Django 4.1.7 on 2023-02-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_de_oferta', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.cliente')),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.comercial')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proyectos.base')),
                ('nombre', models.CharField(max_length=250)),
                ('numero_contrato', models.CharField(max_length=150, verbose_name='Número Contrato')),
                ('estado', models.CharField(choices=[('SI', 'SIN INICIO'), ('I', 'INICIANDO'), ('P', 'PROGRESANDO'), ('A', 'AVANZADO'), ('T', 'TERMINADO')], max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_proyecto', models.BigIntegerField(blank=True, default=0, null=True)),
                ('valor_proyecto_planeado', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Costo Planeado')),
                ('programado', models.FloatField(blank=True, max_length=5, null=True)),
                ('avance', models.FloatField(blank=True, max_length=5, null=True)),
                ('responsable', models.CharField(blank=True, max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.cliente')),
            ],
            options={
                'ordering': ['-creado'],
            },
            bases=('proyectos.base',),
        ),
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proyectos.base')),
                ('costo', models.BigIntegerField(blank=True, default=0, null=True)),
                ('aprobado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=2)),
                ('numero_orden', models.CharField(max_length=20)),
                ('solicitud_de_factura', models.CharField(max_length=20)),
                ('nro_Factura_invein', models.CharField(max_length=20)),
                ('ceco', models.CharField(max_length=20)),
                ('valor_de_venta', models.BigIntegerField(blank=True, default=0, null=True)),
                ('avance', models.FloatField(blank=True, max_length=5, null=True)),
                ('estado', models.CharField(choices=[('SI', 'SIN INICIO'), ('I', 'INICIANDO'), ('P', 'PROGRESANDO'), ('A', 'AVANZADO'), ('T', 'TERMINADO')], max_length=2)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.oferta')),
            ],
            options={
                'ordering': ['-creado'],
            },
            bases=('proyectos.base',),
        ),
        migrations.CreateModel(
            name='Fabricacion',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proyectos.base')),
                ('costo', models.BigIntegerField(blank=True, default=0, null=True)),
                ('aprobado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=2)),
                ('numero_orden', models.CharField(max_length=20)),
                ('solicitud_de_factura', models.CharField(max_length=20)),
                ('nro_Factura_invein', models.CharField(max_length=20)),
                ('ceco', models.CharField(max_length=20)),
                ('valor_de_venta', models.BigIntegerField(blank=True, default=0, null=True)),
                ('avance', models.FloatField(blank=True, max_length=5, null=True)),
                ('estado', models.CharField(choices=[('SI', 'SIN INICIO'), ('I', 'INICIANDO'), ('P', 'PROGRESANDO'), ('A', 'AVANZADO'), ('T', 'TERMINADO')], max_length=2)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.oferta')),
            ],
            options={
                'ordering': ['-creado'],
            },
            bases=('proyectos.base',),
        ),
    ]
