# Generated by Django 4.1.7 on 2023-02-28 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0002_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='objeto',
            field=models.TextField(default='Aaaaaaaaa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CurvaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('programado', models.FloatField(blank=True, max_length=5, null=True)),
                ('avance', models.FloatField(blank=True, max_length=5, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ('creado',),
            },
        ),
    ]
